version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - mvn clean package
  post_build:
    commands:
      - echo Build Complete
artifacts:
  files:
    - target/*.war
    - scripts/stop_server.sh
    - scripts/start_server.sh
    - appspec.yml
   
  discard-paths: yes
