AWSTemplateFormatVersion: 2010-09-09
Description: Template to Create a CodeCommit Repo

Parameters:
  RepoName:
    Type: String
    Description: Name of CodeCommit Repo
    Default: ""

Resources:
  ccDemoAppRepo:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: !Ref RepoName 

Outputs:
  ccDemoAppRepoName:
    Description: CodeCommit Repo Name
    Value: !GetAtt ccDemoAppRepo.Name
    Export:
      Name: ccDemoAppRepoName
  ccDemoAppRepoHTTPCloneURL:
    Description: CodeCommit Repo HTTP Clone URL
    Value: !GetAtt ccDemoAppRepo.CloneUrlHttp
    Export:
      Name: ccDemoAppRepoHTTPCloneURL